# Generated by Django 2.2.7 on 2019-11-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='exam_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
