# Generated by Django 2.2.7 on 2019-11-08 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_courseuser'),
        ('first', '0002_course_exam_date'),
    ]

    operations = [
    ]
